### ISSUE TITLE
如何使用

### ISSUE THREAD

**Issue by lonely-nightmare** [yu1745/websocket_tunnel#2]
支持ipv6嘛?
cdn源站写服务器ip+端口嘛？
回源怎么写呢？
把要加速的域名cname到cdn提供的域名嘛

**Comment by yu1745** [comment]
支持
对
回源host默认就好
对

假如你的mc服务器ip是1.1.1.1，mc服务器端口是25565，server端绑定的端口是80，接入cdn的域名是mc.xxx.com，从cdn那边拿到的加速域名是mc.xxx.com.xxxcdn.com，游戏客户端里的服务器ip是localhost:2022，不开启https，那么编译脚本里的配置就是，
$env:addr="mc.xxx.com.xxxcdn.com:80"
$env:https="false"
$env:listen=":2022"
$env:real="mc.xxx.com"
源站设置1.1.1.1:80，client端不需要参数直接执行，server端执行 server -a :80 -d localhost:25565

**Comment by lonely-nightmare** [comment]
谢谢大佬

**Comment by lonely-nightmare** [comment]
大佬，client 需要玩家在进入服务器的时候一直打开嘛

**Comment by yu1745** [comment]
需要

**Comment by lonely-nightmare** [comment]
可以使其静默启动嘛，不然玩家容易误点关闭，或者来说一直是个黑屏cmd不美观qwq？

**Comment by yu1745** [comment]
在编译脚本编译client的那行后面添加这个 -ldflags="-H windowsgui" 就没有黑框了，但是运行一个来路不明的程序对于玩家来说是很危险的，如果这个程序不是一个显眼的黑框，而是启动了就自动消失不见了，那就更加危险了，完全有理由怀疑这是病毒。所以我认为有这个黑框比没有好，有了这个黑框可以让玩家认为我可以控制这个程序的行为，我想开就开。想关就关，可以让玩家更容易接受这个程序。

**Comment by yu1745** [comment]
在编译脚本编译client的那行后面添加这个 -ldflags="-H windowsgui" 就没有黑框了，但是运行一个来路不明的程序对于玩家来说是很危险的，如果这个程序不是一个显眼的黑框，而是启动了就自动消失不见了，那就更加危险了，完全有理由怀疑这是病毒。所以我认为有这个黑框比没有好，有了这个黑框可以让玩家认为我可以控制这个程序的行为，我想开就开。想关就关，可以让玩家更容易接受这个程序。

**Comment by lonely-nightmare** [comment]
嗷，好知道了
